### ISSUE TITLE
Make #FujiNet device drivers available

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-sd-card#1]
Along with the "fnc-tools" disk image (and the various DOS disk images containing copies of those tools), it would be nice to have a new disk image (or simply add these to the `fnc-tools.atr` and the DOS images, too?) containing drivers for various devices provided by the #FujiNet:

- [x] `Z:` realtime clock device ("`APETIME.COM`" or work-alike?)
- [x] `N:` network device (a la the `AUTORUN.AR0` found in the `connect4.atr` example game)
- [x] `R:` RS232/modem device

**Comment by tschak909** [comment]
Now working on it.
